#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path("../lib", __dir__)
$:.unshift(lib_path) unless $:.include?(lib_path)
require "tailwind_config/cli"

Signal.trap("INT") do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  TailwindConfig::CLI.start
rescue TailwindConfig::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
